### ISSUE TITLE
[COLLISION] Colisión de Entidades

### ISSUE THREAD

**Issue by Lithry** [Aleman5/Des-VJ-III---Game#2]
Descripción: La colisión de los enemigos y el player no corresponden con la perspectiva de la cámara, y reaccionan diferente dependiendo de la posición en la que se encuentren las entidades.

Rate: 100%

Pasos de Reproducción:
1. Comenzar una partida.

Resultado Bug: Me da resultados diferentes a mismas situaciones.

Resultado Esperado: Que el resultado de mismas acciones tenga el mismo resultado.

Archivos:
https://drive.google.com/file/d/1CALD68YTBUkdEyfhQoiyl6TK5_y6BJcA/view?usp=sharing
https://drive.google.com/file/d/1wtBuN3xrJFlLKrP80GjNxzMfyKH8CdXw/view?usp=sharing

**Comment by Aleman5** [comment]
Resuelto
