### ISSUE TITLE
[FEEDBACK] Feedback al comprar Power-Up

### ISSUE THREAD

**Issue by Lithry** [Aleman5/Des-VJ-III---Game#4]
Descripción: Al comprar un power-up, no tengo feedback de ningún tipo que me diga que se realizo la compra.

Reproduction Rate: 100%

Pasos de Reproducción:
1. Comenzar una partida.
2. Conseguir dinero necesario para comprar un power-up.
3. Comprar un power-up.

Resultado: No me da ningún tipo de feedback, sea visual o sonoro, de que se realizo la compra y me obliga a sacar la atención del personaje y mirar el dinero para ver si bajo.

Resultado Esperado: Tener un feedback que me permita saber si la compra se llevo a cabo para no tener que desplazar mi atención del player, aun estando en combate.

Archivos:
https://drive.google.com/file/d/1GdwuK0lXny67TVhiZwhLCUCvBewR8Q9v/view?usp=sharing

**Comment by MatiasRT** [comment]
Para resolver esto necesitamos tener el arte correspondiente, que todavía se está haciendo.
